### ISSUE TITLE
nglite import error 

### ISSUE THREAD

**Issue by sunzhenyang2018** [seung-lab/NeuroglancerAnnotationUI#29]
In src/nglui/\_\_init\_\_.py, line 4, the package nglite is imported. But that package is not available in the pip installed version of nglui. An edit to import neuroglancer as nglite solve the problem (when the environment has neuroglancer installed)

**Comment by ceesem** [comment]
`nglite` is a modification of neuroglancer that is not equivalent with the current pip-installable version of that package. In particular, it is based on a different, older branch that does not have states compatible with the current version.

However, the import in `__init__py` was not intentional nor used (and I'm frankly unsure how it did not throw an error on my development setup), so any modification that prevents an import error probably would have been an effective workaround.

I've released a patch at 3.0.1 that addresses this issue, as well as avoids a neuroglancer python release that has another error.
